Feature/initial wildcard external plugin
oat-sa/rollup-plugin-glob-external pull request #2
Opened 2019-06-27 07:23 UTC by btamas

2019-06-27 13:49 UTC, ferenckiss89 approved these changes
Nice job.

2019-06-28 08:10 UTC, krampstudio requested changes

2019-06-28 08:10 UTC, krampstudio commented on README.md
> +Plugin uses `minimatch` under the hood, so any glob pattern supported.
any glob pattern **is** supported

2019-06-28 08:10 UTC, krampstudio commented on index.spec.js
> +const assert = require('assert');
The license header is missing

2019-06-28 08:24 UTC, krampstudio approved these changes

2019-06-28 08:24 UTC, merged